### ISSUE TITLE
crashes at _fb.isLoggedIn() on IOS 

### ISSUE THREAD

**Issue by anisc** [DrMoriarty/godot-facebook#16]
It work on android but on ios it crashes, is there any thing that need to be added ( framework on xcode or something on the plist ) ?

**Comment by DrMoriarty** [comment]
Thanks for your response. I will check it soon.

**Comment by DrMoriarty** [comment]
I checked this method and it should work as expected.
Try to check frameworks in your project. `facebook.xcframework` should be Embed & Sign. For example my frameworks:
![Снимок экрана 2021-02-08 в 18 16 28](https://user-images.githubusercontent.com/1177068/107239335-cf633e80-6a39-11eb-9631-e5c86ef288c9.png)

**Comment by anisc** [comment]
First, thank you so much for the response and for the plugins
As for the issue here is some screenshots from my code, build and the crache:
![screen3](https://user-images.githubusercontent.com/13128396/107251779-f433c380-69f1-11eb-96f2-8ab999f607c4.png)

![screen1](https://user-images.githubusercontent.com/13128396/107251684-dbc3a900-69f1-11eb-8742-7c08557c7e92.png)
![screen2](https://user-images.githubusercontent.com/13128396/107251738-eb42f200-69f1-11eb-9f00-033927afcd97.png)

**Comment by DrMoriarty** [comment]
It crashes in `login` function. You can see it in your stack.

**Comment by DrMoriarty** [comment]
@anisc I updated plugin to 0.1.5. Check it.

**Comment by anisc** [comment]
It doesn't caches now but still having this error :
2021-02-08 13:10:51.811200-0700 chkobbatn[930:484287] **ERROR**: Condition '!callbackOb' is true.
2021-02-08 13:10:51.811385-0700 chkobbatn[930:484287]    At: /Volumes/Work1/projects/godotframework/plugins/godot-facebook/ios-framework/gdnative_ios/src/Facebook.mm:272:callApi_block_invoke() - Condition '!callbackOb' is true.
I'm pretty sure I'm doing something wrong but what is it ?

**Comment by DrMoriarty** [comment]
@anisc You should provide callback object and method to some api calls. For example: `user_profile(callback_object: Object, callback_method: String)`

**Comment by anisc** [comment]
@DrMoriarty  the part that i don't understand is that it work on android but not on IOS. 
Is the code suppose to be different on different platforms ? this is what I'm using for the user profile 
facebook.user_profile(self,"request _profile success") 
Could you plz show me an exemple?

**Comment by DrMoriarty** [comment]
@anisc There was issue with iOS input parameters. I uploaded v0.1.6, check it please.

**Comment by anisc** [comment]
@DrMoriarty all is perfect thank you so much bro ;)
